kubeshark/kubeshark

cli/cmd/tapRunner.go
cli/kubernetes/provider.go

* Do not tap pods in namespaces which were not requested.

TRA-3360 Fix: Mizu ignores -n namespace flag and records traffic from all pods

---

api/pkg/api/main.go
api/pkg/database/main.go
api/pkg/database/size_enforcer.go
cli/cmd/tap.go

minor performance improvement when pruning the db

TRA-3437 prevent vacuum bottleneck

---

README.md

@IgorGov - one more to request to update documentation - please review and comment whenever you get chance.
It helps knowing about the permissions required for running mizu - I had trouble trying to figure this out until @RamiBerm helped.

Update readme, add prerequisites section

---

tap/har_writer.go

* Never use harRequest.PostData.Params. Always use harRequest.PostData.Text.
* Comment.

Missing request body (#120)

---

cli/cmd/tapRunner.go
cli/fsUtils/mizuLogsUtils.go
cli/mizu/consts.go

A more stable solution would be to filter out mizu pods by label, but I don't want to have to delay the release.

Do not tap pods whose names start with "mizu-".

---

PERMISSIONS.md
README.md

separated permissions section into separate file

---

agent/pkg/models/models.go
agent/pkg/rules/models.go

This reverts commit c4afeee5b3470042c86adf280b75b120883c6197.

Revert "Policy rules remove redundant function (#193)"

---

ui/src/components/EntryDetailed/EntrySections.tsx
ui/src/components/EntryDetailed/Rest/RestEntryDetailsTitle.tsx
ui/src/components/EntryListItem/EntryListItem.tsx

It was probably caused in this PR (https://github.com/up9inc/mizu/pull/211).

Fix TRA-3590 TRA-3589

---

cli/Makefile
cli/README.md.TEMPLATE

added installation instructions to release readme

updated readme for release

---

tap/api/api.go
tap/extensions/http/main.go
ui/src/components/EntriesList.tsx

Related to https://github.com/up9inc/mizu/pull/224

Temporarily fix the filtering into its original state

---

.github/workflows/pr_validation.yml

Fixes the GCC, Go version mismatch in the CI.

Fix the build error in PR validation

---

ui/package-lock.json
ui/package.json

This PR fixes the height issue in scrollbar.

Upgrade `react-scrollable-feed-virtualized` version from `1.4.2` to `1.4.3`

---

cli/cmd/tapRunner.go

Related to https://github.com/up9inc/mizu/pull/304

Watch the tapper pod after starting it

---

.github/ISSUE_TEMPLATE/bug_report.md

Also fix some incorrect information.

Improve formatting in `bug_report.md` issue template

---

ui/src/App.tsx

Introduced by [this change](https://github.com/up9inc/mizu/pull/346/files#diff-3550a8c8813bc37aef982dcb8f241c1756429b859b5ffc0ab9190cc2e3fdb522R33-R48).

Ignore an eslint error

---

agent/pkg/api/socket_routes.go

Introduced by https://github.com/up9inc/mizu/pull/279
The bug was not affecting any stable releases.

Send the message into this WebSocket connection instead of all

---

tap/extensions/http/main.go
tap/extensions/kafka/main.go
tap/extensions/redis/main.go

Also fix the `elapsedTime` for Redis.

Prevent `elapsedTime` to be negative

---

ui/src/components/EntryListItem/EntryListItem.module.sass
ui/src/components/EntryListItem/EntryListItem.tsx

Show the source and destination IP in the entry feed

---

tap/extensions/http/handlers.go
tap/extensions/http/main.go
tap/extensions/http/matcher.go

Add HTTP2 Over Cleartext (H2C) support

---

ui/src/components/EntryDetailed.tsx
ui/src/components/EntryDetailed/EntryViewer.module.sass
ui/src/components/EntryListItem/EntryListItem.tsx
ui/src/components/TrafficPage.tsx

Show the `EntryItem` as `EntrySummary` in `EntryDetailed` [TRA-3983 alternative 7]

---

ui/src/components/EntryDetailed/EntrySections.tsx

Fix the CSS issue in `Queryable` inside `EntryViewLine`

---

Dockerfile
debug.Dockerfile
ui/package-lock.json
ui/package.json
ui/src/components/EntriesList.tsx
ui/src/components/EntryListItem/EntryListItem.module.sass
ui/src/components/EntryListItem/EntryListItem.tsx
ui/src/components/Filters.tsx

Include milliseconds information into the timestamps in the UI

---

ui/src/components/EntryListItem/EntryListItem.tsx
ui/src/components/TrafficPage.tsx

https://user-images.githubusercontent.com/2502080/146283751-036927cc-161c-47cd-8f4a-0dc9d447d58b.mp4

Change the connection status text and the toggle connection behavior

---

tap/extensions/amqp/helpers.go
ui/src/components/EntriesList.tsx

Not vital errors but errors nevertheless.

Fix a JavaScript error in case of `null` attribute and an interface conversion error in the API server

---

ui/src/components/EntryListItem/EntryListItem.module.sass

Make `EntryItem` more responsive

---

README.md

Fixing Mizu url in readme

---

ui/src/components/EntryListItem/EntryListItem.tsx

Fixes the build error that's introduced by https://github.com/up9inc/mizu/pull/614

Fix the build error

---

tap/extensions/http/helpers.go
tap/extensions/http/main.go

Show HTTP path segments as a list of strings in the right pane

---

agent/pkg/api/socket_routes.go
agent/pkg/controllers/user_controller.go
agent/pkg/middlewares/requiresAuth.go
ui/src/helpers/api.js

This ends up preventing local FE development, rolling back for now

Revert "TRA-4157 fix ws auth (#669)"

---

tap/extensions/http/helpers.go
tap/extensions/http/main.go

TRA-4139 Merge repeated keys in query parameters into arrays

---

tap/extensions/redis/read.go

Tested against the traffic sourced from the integration tests of https://github.com/go-redis/redis

TRA-4240 Fix the interface conversion and index out of range errors in the Redis dissector

---

cli/config/configStruct.go

This reverts commit 70cef9dc4bef15af9f27d576f690d2d9f85d99f9.

Revert "Fix: show agent-image in config after generation (#717)"

---

ui/src/components/EntryDetailed/EntrySections.tsx

Fix protobuf prettify logic

---

.github/workflows/release.yml
cli/cmd/version.go
cli/config/configStruct.go
cli/mizu/consts.go
cli/mizu/version/versionCheck.go
cli/pkg/version/version.go
cli/pkg/version/version_test.go
cli/telemetry/telemetry.go

Example of how versioning will look:
https://github.com/IgorGov/mizu/releases

Moving from Semver to major.patch versioning

---

Makefile

Add `test-lint` Makefile rule

---

cli/cmd/checkRunner.go

Fix: mizu check when mizu not running

---

.github/workflows/release.yml
README.md

Also fixes the styling issue in the badges.

Create and push the `latest` tag if the branch is `main` (stable)

---

agent/pkg/elastic/esClient.go
agent/pkg/oas/oas_generator.go
agent/pkg/servicemap/servicemap.go

Revert "Support stopping oas/servicemesh/telemetry in flight"

---

Dockerfile
agent/go.mod
agent/go.sum
cli/go.mod
cli/go.sum
ui/src/helpers/api.js

Brings in these changes;
- https://github.com/up9inc/basenine/releases/tag/v0.6.0
- https://github.com/up9inc/basenine/releases/tag/v0.6.1
- https://github.com/up9inc/basenine/releases/tag/v0.6.2
- https://github.com/up9inc/basenine/releases/tag/v0.6.3
Reduces memory usage and performance drawbacks after database truncation (size limiting).
Fixes some issues in the Basenine Go client.
URL encodes the query in the front-end code.
Adds [wildcard selector](https://github.com/up9inc/basenine/wiki/BFL-Syntax-Reference#wildcard-selector) support to the filter syntax.
Adds the time helpers below:
- [`now`](https://github.com/up9inc/basenine/wiki/BFL-Syntax-Reference#now-integer)
- [`seconds`](https://github.com/up9inc/basenine/wiki/BFL-Syntax-Reference#secondsinteger-integer)
- …

Upgrade to Basenine `v0.6.3`, add `xml` and time helpers, make `xml` and `json` helpers available in `redact` helper

---

acceptanceTests/cypress/integration/testHelpers/TrafficHelper.js
acceptanceTests/cypress/integration/tests/UiTest.js

after https://github.com/up9inc/mizu/pull/897 there are some broken tests and this PR fixes them

Fix acceptance test

---

.github/workflows/static_code_analysis.yml

Adding conditions to static code analysis validation in CI, so it won't run / fail when the only changes in the UI for instance:
https://github.com/up9inc/mizu/pull/966

Add conditional Go lint validation to CI

---

agent/pkg/oas/oas_generator.go

* Added log message
* Remove Reset function from OasGenerator interface, use Stop+Start instead
* SetEntriesQuery returns a bool stating whether the query changed

Make minor changes to OasGenerator

---

tap/extensions/amqp/Makefile
tap/extensions/http/Makefile
tap/extensions/kafka/Makefile
tap/extensions/redis/Makefile

This PR is caused by these two:
- https://github.com/up9inc/mizu/pull/876
- https://github.com/up9inc/mizu/pull/974

Fix the unit tests of protocol extensions

---

.github/workflows/acceptance_tests_on_pr.yml

the acceptance test will be triggered by '#run_acceptance_tests' string in commit message

Trigger by commit message acceptance test on PR to develop

---

agent/pkg/entries/entries_provider.go

Introduced by https://github.com/up9inc/mizu/pull/949
> Ignore `[Unresolved]` in the screenshots, it's a local run.

`GetEntry` unmarshaling error indicates an error message sent by the database server

---

ui-common/src/hooks/WindowDimensionsHook.tsx

window width changes the headlines when size getting smaller

TRA-4513_grpc heading overlap request size 

---

acceptanceTests/cypress/integration/tests/UiTest.js

Related to:
- https://github.com/up9inc/mizu/pull/1074
- https://github.com/up9inc/mizu/pull/1056

Handle the wait for fetch in acceptance tests better

---

acceptanceTests/cypress/integration/tests/UiTest.js

Follow up on https://github.com/up9inc/mizu/pull/1088

Fix `checkFilter` method in the acceptance tests

---

ui-common/src/components/TrafficViewer/EntryListItem/EntryListItem.tsx

TRA-4282- change icon style css to move the icon so it can be clicked when hover over dst ip

---

cli/cmd/install.go
cli/cmd/installRunner.go
cli/config/configStructs/installConfig.go

Updated the install command UX to look like:

Updated the install command UX

---

ui-common/src/components/UI/style/SelectList.module.sass

list takes 100% from parent

---

agent/pkg/replay/replay.go

Fixes this issue in Represent function: 
(it is solved when the entry is Marshaled and UnMarshaled)
```
interface conversion: interface {} is []string, not []interface {}
/usr/local/go/src/runtime/iface.go:261 (0x40bd14)
/app/tap/extensions/http/main.go:377 (0x167b1f4)
/app/tap/extensions/http/main.go:509 (0x167bc75)
/app/agent-build/pkg/replay/replay.go:139 (0x1737d8e)
/app/agent-build/pkg/controllers/replay_controller.go:32 (0x1928d4a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1729fb8)
/app/agent-build/pkg/middlewares/cors.go:17 (0x1729fa4)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x1a71438)
/app/agent-build/main.go:221 (0x1a71424)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x9c47c1) …
```

Fix replay Endpint 

---

ui-common/src/components/modals/ServiceMapModal/ServiceMapModal.module.sass
ui-common/src/components/modals/TrafficStatsModal/TimelineBarChart/TimelineBarChart.tsx
ui-common/src/components/modals/TrafficStatsModal/TrafficPieChart/TrafficPieChart.tsx
ui-common/src/components/modals/TrafficStatsModal/TrafficStatsModal.tsx
ui-common/src/components/modals/TrafficStatsModal/consts.ts
ui-common/src/index.tsx
ui/src/components/Pages/TrafficPage/TrafficPage.tsx

cleaning the following warnings:

warning cleaning from console

---

ui-common/src/components/modals/TrafficStatsModal/TimelineBarChart/TimelineBarChart.module.sass
ui-common/src/components/modals/TrafficStatsModal/TrafficPieChart/TrafficPieChart.module.sass
ui-common/src/components/modals/TrafficStatsModal/TrafficPieChart/TrafficPieChart.tsx
ui-common/src/components/modals/TrafficStatsModal/TrafficStatsModal.module.sass
ui-common/src/components/modals/TrafficStatsModal/TrafficStatsModal.tsx
ui-common/src/variables.module.scss

Grooming Traffic Stats Modal - change font and time picker position

---

README.md

I've added instruction on how to install kubeshark via brew

docs: add how to install step for brew

---

helm-chart/templates/09-worker-daemon-set.yaml

Should be merged after https://github.com/kubeshark/worker/pull/39

Pass kernel-module flag only if pf_ring enabled

---

helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/12-config-map.yaml

added a variable to the config-map
added an env var both at the hub and worker that references the varable in the config-map

Add API cloud endpoint env var to hub deployment

---

config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/values.yaml
manifests/complete.yaml

**What's changed:**
Support `showAdminConsoleLink` authorized action.
Please, refer to corresponding PRs in `front` & `hub` to get more info.

✨ Feature-based SAML authorization (#49)

---

helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/12-config-map.yaml

1. removed cloud URL from config map
2. added to hub's and worker's deployments

removed cloud URL from config map

---

install.sh

Towards https://github.com/kubeshark/kubeshark/issues/1488
If kubeshark was installed with brew before, it will be removed first

Remove brew version before installing with script

---

.github/workflows/release.yml

Towards https://github.com/kubeshark/kubeshark/issues/1488

Add homebrew core version update release step

---

helm-chart/templates/16-network-policies.yaml

Towards https://github.com/kubeshark/hub/issues/59

Add network policies for kubeshark components

---

config/configStructs/tapConfig.go
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/values.yaml
manifests/complete.yaml

Please, refer to the respective disable-features PRs in `hub` & `front`.

🔨 Disable scripting, targeted pods update & recording via `ConfigMap` keys

---

helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/05-hub-service.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/07-front-service.yaml

Needs also release of frontend first after merging https://github.com/kubeshark/front/pull/134

Switch to lower ports

---

.github/workflows/release.yml

Move brew release steps into separate jobs so in case of failure it can be restarted independently

Move brew release into separate job

---

config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/values.yaml
manifests/complete.yaml

Please, refer to a corresponding PR for setting custom timezone in `kubeshark/front`.

✨ Set custom timezone

---

helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/12-config-map.yaml

- Consider cloudLicenseEnabled only if license is empty. If license isn't empty disregard cloudLicenseEnabled

Disable cloud auth when license is present

---

helm-chart/templates/06-front-deployment.yaml

**Issue:**
Please, refer to the _"Enable/Disable traffic capture CTA"_ `front` issue.

🔨 Add `REACT_APP_STOPPED` env to `front`

---

config/configStructs/tapConfig.go
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/values.yaml

Please, refer to the corresponding issue.

🔨 Add `tap.stopTrafficCapturingDisabled` flag

---

config/configStruct.go
helm-chart/templates/06-front-deployment.yaml
helm-chart/values.yaml

Please, refer to the corresponding issue for the info.

:hammer: Support chat flag

---

helm-chart/values.yaml

Following metrics data from our test environments

Increase default requests/limits

---

config/configStructs/tapConfig.go
helm-chart/values.yaml

Towards https://github.com/kubeshark/devops/issues/7

Adjust resources limits

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

Replaces https://github.com/kubeshark/kubeshark/pull/1605
Towards https://github.com/kubeshark/hub/issues/168

Add sentry related configurations

---

helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml

fix: respect `tap.docker.imagePullSecrets`

---

helm-chart/templates/09-worker-daemon-set.yaml

To complement:
- https://github.com/kubeshark/kubeshark/pull/1610

🐛 Fix `-staletimeout` worker command value

---

config/configStructs/tapConfig.go
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/values.yaml

Please, refer to the corresponding issue.

🔨 Add `tap.presetFiltersChangingEnabled` helm value

---

helm-chart/templates/02-cluster-role.yaml

Towards https://github.com/kubeshark/worker/issues/345

Add networkpolicies permissions

---

helm-chart/templates/02-cluster-role.yaml

Towards https://github.com/kubeshark/hub/issues/210
Required for namespaceSelector filtering

Add permissions to watch namespaces

---

cmd/scripts.go

fixed a bug where a new script can't be added if

---

cmd/pcapDump.go
cmd/pcapDumpRunner.go
config/configStructs/tapConfig.go

Changes:
- add new param --time to set the max time interval for which we copy the pcaps
- remove obsolete params

Add --time param to pcapdump

---

helm-chart/values.yaml

Please, refer to the corresponding task regarding Role/Authorization for Scripting actions.

🛂 Create save/activate/delete role scripting permissions

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/values.yaml
manifests/complete.yaml

Towards https://github.com/kubeshark/kubeshark/pull/new/change-worker-port-to-48999

Replace sniffer 30001 port with 48999

---

helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

to Sniffer in case eBPF traffic capture mechanism is used.

Added security capabilities, especially IPC_LOCK

---

config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/values.yaml
manifests/complete.yaml

Please, refer to the corresponding issue related to Scripting authorization permissions.

🛂 Add save/activate/delete role scripting permissions

---

helm-chart/templates/09-worker-daemon-set.yaml
manifests/complete.yaml

This reverts commit 12f888305206f3ae28b5e51ba979b2b62336fee2.

Revert "Revert "Initialize kubeshark pinned eBPF resources inside init container (#1665)" (#1676)"

---

cmd/pcapDumpRunner.go
config/configStructs/tapConfig.go
helm-chart/templates/12-config-map.yaml
helm-chart/values.yaml

Remove pcap Src from configMap and move to a pre-defined value instead.

#528 Remove pcap src from configMap

---

config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

Towards https://github.com/kubeshark/devops/issues/41

Make node selector component specific

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

Towards https://github.com/kubeshark/devops/issues/42

Add dns config

---

helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml

Towards https://github.com/kubeshark/kubeshark/issues/1702

Fix pull secret aligning

---

cmd/pcapDumpRunner.go

Update the name of the merged file to contain cluster UID and date/time.

#537 Update name of the merged file

---

helm-chart/templates/02-cluster-role.yaml

Towards https://github.com/kubeshark/hub/issues/321

Allow reading logs

---

config/configStruct.go

**To support:**
- https://github.com/kubeshark/kubeshark/pull/1737

:hammer: Add default value for Dex node selector terms

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/08-persistent-volume-claim.yaml
helm-chart/values.yaml

Replacement for https://github.com/kubeshark/kubeshark/pull/1738
Requires https://github.com/kubeshark/kubeshark/pull/1740 to be merged first

Add pvc volumeMode

---

config/configStruct.go
helm-chart/README.md
helm-chart/templates/NOTES.txt
helm-chart/values.yaml

Make changes in default values

---

helm-chart/templates/02-cluster-role.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/templates/13-secret.yaml
helm-chart/templates/18-cleanup-job.yaml
manifests/complete.yaml

Towards https://github.com/kubeshark/hub/issues/273
Actual cm/secret will be created by hub during startup so that gitops stuff doeesn't rewrite those on update
Also add cleanup job that deletes dynamically created cm/secret

Add kubeshark cm and secret -default suffix

---

config/configStructs/tapConfig.go
helm-chart/values.yaml

Towards https://github.com/kubeshark/worker/issues/653

Decrease initial delay seconds

---

config/configStruct.go
helm-chart/values.yaml
manifests/complete.yaml

disable syscall by default as it is a significant

---

helm-chart/templates/18-cleanup-job.yaml

Towards https://github.com/kubeshark/devops/issues/61

Run cleanup program instead of kubectl

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/templates/13-secret.yaml
helm-chart/templates/18-cleanup-job.yaml
helm-chart/templates/_helpers.tpl
helm-chart/values.yaml
manifests/complete.yaml

In this mode configmap/secret are created from default cm/secret

Add optional gitops mode

---

Makefile

Towards https://github.com/kubeshark/kubeshark/issues/1752

Use full semver version in Chart.yaml

---

errormessage/errormessage.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml

fix some minor issues in the comments

chore: fix some minor issues in the comments

---

config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/12-config-map.yaml
helm-chart/values.yaml

Towards https://github.com/kubeshark/hub/issues/395
Cancel capture after specified period of time with no active connections with workers

Add stopAfter option to disable capture when inactive
