kubeshark/kubeshark

cli/cmd/tapRunner.go
cli/kubernetes/provider.go

1. CLI will not crash if there are no pods matching the regex. Instead it will print a warning and continue to watch the pods.
2. If the number of tapped pods decreases to 0 (at a later stage), CLI will delete mizu-tapper daemonset.
3. Attempting to delete resources that are not installed will not cause an error.

Fix crash when there are no pods matching the regex

---

cli/kubernetes/provider.go

Set resource requests and limits.
Aggregator (based on sock-shop during load test):
- limit cpu: 750m
- limit memory: 512Mi
- request cpu: 50m
- request memory: 50Mi
Tapper (limits are identical to passive-tapper’s limit in a regular up9 install):
- limit cpu: 500m
- limit memory: 1Gi
- request cpu: 50m
- request memory: 50Mi
Set low request values in order to ensure that Mizu starts successfully.

TRA-3410 Resource limits

---

api/pkg/resolver/loader.go

If KUBECONFIG environment variable is set, use it. Otherwise default to ~/.kube/config

Support KUBECONFIG environment variable.

---

tap/har_writer.go

For requests with multipart/form-data or application/x-www-form-urlencoded media-types, martian/har will parse the request body and place the parameters in harRequest.PostData.Params instead of harRequest.PostData.Text (as the HAR spec requires it). Mizu currently only looks at PostData.Text. Therefore, instead of letting martian/har set the content of PostData, always copy the request body to PostData.Text.

Missing request body

---

Makefile
build-push-featurebranch.sh
cli/Makefile

Mizu can now be built with:
```sh
make docker
make cli
```
No need to fuss around with `SEM_VER` / docker tags.
CLI and agent versions will match each other, so CLI will use the correct image and `fetch`/`view` commands will work out of the box.
CD will not be affected because it explicitly sets `SEM_VER`.
`SEM_VER` can be set to a specific value via either a makefile variable or an environment variable.
```sh
make docker SEM_VER=1.2.3
make cli SEM_VER=1.2.3
#option 2
export SEM_VER=1.2.3
make docker
make cli
```

Added a default SEM_VER

---

README.md

change prerequisite to permissions and kubeconfig. These are more FYIs as Mizu requires very little prerequisites. 
Change the description to match getmizu.io

some changes in the read me

---

agent/pkg/controllers/entries_controller.go
tap/api/api.go
tap/extensions/amqp/helpers.go
tap/extensions/amqp/main.go
tap/extensions/http/handlers.go
tap/extensions/http/main.go
tap/extensions/http/matcher.go
tap/extensions/kafka/main.go
tap/extensions/kafka/request.go
tap/extensions/kafka/response.go
tap/tcp_reader.go
tap/tcp_stream.go
tap/tcp_stream_factory.go
ui/src/components/EntryDetailed.tsx

Related to https://github.com/up9inc/mizu/pull/224
Fixes the body size. It was in the `har.Entry.Response.BodySize` before https://pkg.go.dev/github.com/google/martian/har#Response https://github.com/up9inc/mizu/blob/17fa163ee310d94c3c6efea0509b014312290842/agent/pkg/models/models.go#L206
fetched through
https://github.com/up9inc/mizu/blob/7f2021c312ddc5249ba2f02dc7c6332acb12bb21/ui/src/components/HarEntryDetailed.tsx#L33
Fixes the receive (elapsed time). It's https://pkg.go.dev/github.com/google/martian/har#Timings Calculated just as before https://github.com/up9inc/mizu/blob/17fa163ee310d94c3c6efea0509b014312290842/tap/har_writer.go#L101
Fixes the timestamps. Now they come from https://github.com/up9inc/mizu/blob/71d5b10f56ca0e6738330f341ffb9c7a3cbc071d/tap/tcp_reader.go#L72 just as …

Fix body size, receive (elapsed time) and timestamps

---

tap/api/api.go
tap/extensions/amqp/helpers.go
tap/extensions/http/main.go
tap/extensions/kafka/helpers.go

Moves them to a single place to reduce duplication.

Turn `table` and `body` strings to constants and move them to extension API

---

.gitignore
cli/kubernetes/provider.go
shared/consts.go
tap/extensions/amqp/main.go
tap/extensions/amqp/read.go
tap/extensions/amqp/spec091.go
tap/extensions/amqp/types.go
tap/extensions/http/handlers.go
tap/passive_tapper.go
tap/settings.go

Related to https://github.com/up9inc/mizu/pull/224
Sets maximum AMQP message size to 16MB
Adds one more fail-fast that checks max. header frame size of AMQP.
Sets `GOGC` to `12800` to trigger garbage collector less.
Does improvements in `startMemoryProfiler` method:
- Introduces `MEMORY_PROFILING_DUMP_PATH` environment variable.
- Introduces `MEMORY_PROFILING_TIME_INTERVAL` environment variable.
`GOGC`'s value is the criteria for Go's garbage collector triggering. It means the change in percentage of maximum allocated space compared to previous collection.
The dissectors constantly do allocations and quickly free them. This causes a lot of garbage collector triggering if it's set to `100`. A value like `12800` makes it less triggered. It actually reduces avg. memory usage because GC is …

Fix the memory exhaustion by optimizing max. AMQP message size and `GOGC`

---

tap/api/api.go
tap/extensions/amqp/main.go
tap/extensions/http/main.go
tap/extensions/kafka/main.go
tap/passive_tapper.go
tap/settings.go
tap/stats_tracker.go
tap/tcp_reader.go
tap/tcp_stream.go
tap/tcp_stream_factory.go

Related to https://github.com/up9inc/mizu/pull/224
Closes the hanging TCP message channels after a dynamically aligned timeout (base `500000` milliseconds).
https://github.com/up9inc/mizu/blob/aa24ee37791ca00741dbfb0f78e9334d6a3b344f/tap/passive_tapper.go#L98
Since all ports are listened now, in most cases,
https://github.com/up9inc/mizu/blob/f13152d619004de98d15b191e4ca3e1a3e37b97b/tap/tcp_stream.go#L166
is not called. Therefore the channels do not close:
https://github.com/up9inc/mizu/blob/f13152d619004de98d15b191e4ca3e1a3e37b97b/tap/tcp_reader.go#L52
and in some cases Goroutines pile up. Because `Read` does not return (falls into infinite loop):
https://github.com/up9inc/mizu/blob/f13152d619004de98d15b191e4ca3e1a3e37b97b/tap/tcp_reader.go#L69
This PR closes the TCP message channels …

Stop the hanging Goroutines by dropping the old, unidentified TCP streams

---

tap/passive_tapper.go
tap/settings.go
tap/tcp_stream_factory.go

This PR;
- Fixes the `OOMKilled` error by calling `debug.FreeOSMemory` periodically.
- Removes `MAX_NUMBER_OF_GOROUTINES` environment variable.
- Increases the default value of `TCP_STREAM_CHANNEL_TIMEOUT_MS` environment variable's value to `10000`.

Fix the `OOMKilled` error by calling `debug.FreeOSMemory` periodically

---

cli/cmd/tap.go
cli/cmd/tapRunner.go
cli/config/configStructs/tapConfig.go
docs/POLICY_RULES.md

Added:
- --traffic-validation on `tap cli` and inside the `config` file
- Deprecation Warning on --test-rules on CLI and config file
```bash
❯ go run mizu.go tap
Mizu will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
--test-rules is DEPRECATED and will be removed on the next release. Use --traffic-validation instead
Tapping pods in namespaces "sock-shop"
```

[Refactor/TRA-3692] rename test rules to traffic validation

---

tap/extensions/http/sensitive_data_cleaner.go

`:authority` pseudo-header field is the virtual host name of authority and it's a crucial component of address resolution in HTTP/2. So don't redact it.
References:
- https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3
- https://grpc.github.io/grpc/core/md_doc_naming.html
- https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests
From:
To:

Don't redact `:authority` pseudo-header field

---

agent/pkg/api/main.go
tap/api/api.go
tap/extensions/amqp/main.go
tap/extensions/http/main.go
tap/extensions/kafka/main.go

Since the `Latency` field was being omitted, the boolean expression below was becoming `false`:
https://github.com/up9inc/mizu/blob/43f44af0dd2f376bf508551b36bb800787a160c4/ui/src/components/EntryListItem/EntryListItem.tsx#L71-L77
The **rules.yaml** file below reproduces it:
```yaml
rules:
- name: latency-test
type: latency
latency: 1
service: ".*"
path: "/*"
```
Before:
After:

Don't omit the `Latency` field in `BaseEntryDetails`

---

ui/src/components/EntryDetailed.tsx
ui/src/components/EntryDetailed/EntryViewer.tsx
ui/src/components/UI/Tabs.tsx

This PR omits the the `RESPONSE` tab and `elapsedTime` if the `response` is empty.

Omit the `RESPONSE` tab and `elapsedTime` if the `response` is empty

---

agent/pkg/api/main.go
agent/pkg/controllers/entries_controller.go
agent/pkg/models/models.go
agent/pkg/rules/rulesHTTP.go
cli/kubernetes/provider.go
tap/api/api.go
ui/src/App.tsx
ui/src/components/EntryDetailed.tsx
ui/src/components/EntryDetailed/EntrySections.tsx
ui/src/components/EntryDetailed/EntryViewer.tsx

This PR omits the `RULES` tab if the policy rules feature is inactive.
`--traffic-validation-file` option is **not** supplied:
`--traffic-validation-file` option is supplied:

Omit the `RULES` tab if the policy rules feature is inactive

---

tap/api/api.go

This PR fixes a bug that's introduced by [this line](https://github.com/up9inc/mizu/commit/616eccb2cfb13bf0259fad1b0d00afd0f53adc35#diff-06c31b5369dee97f15b8108f8d13c4283d4e056e340b5762e195f4957924e755R107) which causes the right-pane to look like HTTP/1.1 while it's HTTP/2.
Before:
After:

Fix the typo in `protocolAbbreviation` field of `MizuEntry`

---

tap/extensions/redis/helpers.go
tap/extensions/redis/main.go

Fix a server-side error:
```text
[GIN] 2021/09/28 - 15:55:37 | 500 |  295.725921ms |       127.0.0.1 | GET      "/api/entries/61533af99122c03b8b8345e5"
2021/09/28 15:56:07 [Recovery] 2021/09/28 - 15:56:07 panic recovered:
interface conversion: interface {} is map[string]interface {}, not map[string]string
/usr/local/go/src/runtime/iface.go:261 (0x7f8d79a803f7)
/app/tap/extensions/redis/main.go:144 (0x7f8d79b95364)
/app/agent-build/pkg/controllers/entries_controller.go:143 (0x1fe2ad9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x1fe75e2)
/app/agent-build/main.go:203 (0x1fe75c9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x1fe70db)
/app/agent-build/main.go:187 (0x1fe70c2)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165 (0x11a4f79) …
```

Fix a `500` error caused by an interface conversion in Redis

---

cli/kubernetes/provider.go

Related to https://github.com/up9inc/mizu/pull/309
Prevents WebSocket connection errors from tappers to the API server by adding readiness and liveness probes to API server.

Add readiness and liveness probes to API server

---

tap/extensions/http/handlers.go

Introduced by https://github.com/up9inc/mizu/commit/29ba963c48b5bdb82fbd20b71cbb39d591c7b9af (the latest commit)
`kubectl logs --follow mizu-tapper-daemon-set-wf7n9 -n mizu`
```
2021-10-19T13:06:41.387Z INFO ▶ 1 main.go:138 loadExtensions ▶ Loading extension: amqp.so
2021/10/19 13:06:41 Initializing AMQP extension...
2021-10-19T13:06:41.393Z INFO ▶ 1 main.go:138 loadExtensions ▶ Loading extension: http.so
2021/10/19 13:06:41 Initializing HTTP extension...
2021-10-19T13:06:41.398Z INFO ▶ 1 main.go:138 loadExtensions ▶ Loading extension: kafka.so
2021/10/19 13:06:41 Initializing Kafka extension...
2021-10-19T13:06:41.403Z INFO ▶ 1 main.go:138 loadExtensions ▶ Loading extension: redis.so
2021/10/19 13:06:41 Initializing Redis extension...
2021-10-19T13:06:41.411Z INFO ▶ 1 main.go:163 …
```

Bring back the lines that didn't mean to be removed

---

Dockerfile
cli/apiserver/provider.go
cli/mizu/version/versionCheck.go
debug.Dockerfile

This PR;
Sets a default value for `SEM_VER` build-time variable in `Dockerfile`
Also fixes a runtime error that happens when the API server's version is not a valid SemVer:
```
$ ./cli/bin/mizu__ view                                                                                                                                                                                       ok  10s  17:52:37 
Establishing connection to k8s cluster...
Mizu is available at http://localhost:8899/mizu
Update available! 0.0.0 -> 0.18.0 (curl -Lo mizu https://github.com/up9inc/mizu/releases/download/0.18.0/mizu_linux_amd64 && chmod 755 mizu)
Unhandled panic: runtime error: index out of range [0] with length 0
stack: goroutine 1 [running]:
runtime/debug.Stack(0xc00011f558, 0x21a8180, 0xc0001544b0) …
```

Set a default value for `SEM_VER` build-time variable in `Dockerfile`

---

ui/.snyk

Dependency tree:
`node-sass@5.0.0 > node-gyp@7.1.2 > request@2.88.2 > http-signature@1.2.0 > jsprim@1.4.1 > json-schema@0.2.3`
`node-sass` should fix it first.

Ignore `SNYK-JS-JSONSCHEMA-1920922`

---

Dockerfile
debug.Dockerfile

Fixes `limit` helper being not finished because of lack of meta updates.
The issue introduced by https://github.com/up9inc/mizu/pull/452

Upgrade Basenine version from `0.2.8` to `0.2.9`

---

agent/pkg/controllers/entries_controller.go
ui/src/components/TrafficPage.tsx

`404` happens if the entry is removed because of database size limit (200MB by default). So we display a toast message to inform the user about inexistence of the entry.

Return `404` instead of `500` if the entry could not be found and display a toast message

---

ui/src/components/UI/FancyTextDisplay.tsx

Introduced by https://github.com/up9inc/mizu/pull/478 not present in a stable release.
Prevents:

Prevent the crash on client-side in case of `text` being undefined in `FancyTextDisplay`

---

tap/extensions/http/main.go

Introduced by https://github.com/up9inc/mizu/pull/492 (not present in a stable release)

Remove `SetHostname` method in HTTP extension

---

cli/apiserver/provider.go

I encountered an error and it was hard to investigate due to lack of proper logs.
If a Kubernetes user doesn't have permissions to `services/proxy` in its rbac roles, the cli fail to connect to the api-server. The logs shows response code 403 but no more than that.
The api-server on the other hand, shows everything is fine - because kubernetes didn't even pass the request to it.
This PR add the response body to the log message in case of failure, it may help others with bad rbac.

Add response body to the error in case of failure

---

tap/extensions/http/main.go

Rename `URL` field to `Target URI` in the UI to prevent confusion

---

ui/src/components/EntryDetailed/EntrySections.tsx

Hide `Encoding` field if it's `undefined` or empty in the UI

---

agent/pkg/api/socket_routes.go
agent/pkg/models/models.go
shared/models.go
ui/src/components/EntryDetailed.tsx
ui/src/components/EntryListItem/EntryListItem.tsx
ui/src/components/TrafficPage.tsx

Introduces a slight delay in case of network bottleneck:
https://user-images.githubusercontent.com/2502080/144033464-a9944bbd-b051-4720-86fd-63c3a8827bee.mp4
https://user-images.githubusercontent.com/2502080/144034777-59e128ee-a882-4908-8079-815b5a64cfc0.mp4
No racing, no incorrect behavior.

Fix the selected entry behavior by propagating the `focusedEntryId` through WebSocket (before #452) TRA-3983

---

ui/src/components/EntryListItem/EntryListItem.module.sass
ui/src/components/UI/StatusCode.tsx
ui/src/components/UI/Summary.tsx

Introduced by https://github.com/up9inc/mizu/pull/512

Fix the styling of `Queryable` under `StatusCode` and `Summary` components

---

ui/src/components/EntryListItem/EntryListItem.module.sass
ui/src/components/EntryListItem/EntryListItem.tsx
ui/src/components/UI/Protocol.tsx
ui/src/components/UI/StatusCode.tsx

Fixes the plus icon for the queryable vertical protocol element that was not clickable because of a CSS issue.

Fix the CSS issues in queryable vertical protocol element

---

ui/src/components/EntriesList.tsx
ui/src/components/TrafficPage.tsx

Fixes the glitch in the UI that's caused by opening an additional WebSocket connection when "Snap to bottom" button is clicked.
https://user-images.githubusercontent.com/2502080/146092435-72da2703-efe0-45e1-961d-7da2615df220.mp4
https://user-images.githubusercontent.com/2502080/146092468-b57d8cac-cd06-4c79-85be-bb1509a1a27b.mp4

Fix the glitch

---

ui/src/components/EntryListItem/EntryListItem.tsx

Introduced by https://github.com/up9inc/mizu/pull/525
> Note: Mouse cursor is actually hovering on the related element. It's just I forgot to enable mouse cursor while taking the screenshots. (`front-end.sock-shop` which is `src.name` field on right-pane)
See how the plus icon is misplaced on hover;

Fix the CSS issue in `Queryable` component for `src.name` field on heading mode

---

ui/src/components/TrafficPage.tsx

The warning is introduced with https://github.com/up9inc/mizu/pull/542

Fix `React Hook useEffect has a missing dependency: 'handleQueryChange'` warning

---

tap/tcp_assembler.go
tap/tcp_stream.go
tap/tcp_stream_factory.go

The diff to demonstrate how the amount of logs in tapper daemon set pod, can be reduced in case of debug level is `DEBUG`.

Remove TCP related logging to reduce the amount of logs on `DEBUG` level

---

.github/workflows/acceptance_tests.yml
acceptanceTests/logs_test.go
acceptanceTests/tap_test.go
acceptanceTests/testsUtils.go
cli/mizu/fsUtils/mizuLogsUtils.go
docs/CONFIGURATION.md
shared/kubernetes/provider.go

Also includes the container name into the log fetching function. So log filenames become:
```
mizu.mizu-api-server.basenine.log
mizu.mizu-api-server.mizu-api-server.log
```
Related PRs:
- https://github.com/up9inc/mizu/pull/603
- https://github.com/up9inc/mizu/pull/583

Fix the acceptance tests and a typo in `CONFIGURATION.md`

---

ui/src/components/EntriesList.tsx
ui/src/components/TrafficPage.tsx

This has been done like that without realizing the design specification states the play button snaps to the bottom as well. With this change it's fixed to the software specification.

Make the scrollable reference snap to the bottom after clicking pause/play buttons (resuming streaming)

---

ui/src/components/EntryDetailed/EntrySections.tsx

Ignore the unresolved `src.name` and `dst.name` fields. It's because I'm running it locally.

Sort key-value pairs on client-side in `EntryTableSection`

---

tap/extensions/redis/helpers.go
ui/src/components/EntryDetailed/EntrySections.tsx
ui/src/components/EntryDetailed/EntryViewer.tsx

Ignore the unresolved `src.name` and `dst.name` fields. It's because I'm running it locally.

Display Redis value as `EntryBodySection`

---

ui/src/components/EntryListItem/EntryListItem.tsx

Fixes;
Introduced by https://github.com/up9inc/mizu/commit/5fed5808d228553c07e053df77b96f8da7349fc8#diff-c77e7a49451f5f399438adaf74d06341ea85aaf641b9d502975a09606aa9e5e8R54

Fix `EntryItem` border on heading mode

---

agent/pkg/api/socket_routes.go
agent/pkg/controllers/user_controller.go
agent/pkg/middlewares/requiresAuth.go
ui/src/helpers/api.js

browser websockets do not allow appending custom http headers to the initial request, to work around this I switched our auth to be cookie based rather than custom header based (browser websockets automatically send cookies).

TRA-4157 fix ws auth

---

agent/pkg/api/main.go
agent/pkg/oas/counters.go
agent/pkg/oas/feeder_test.go
agent/pkg/oas/oas_generator.go
agent/pkg/oas/specgen.go
agent/pkg/oas/test_artifacts/params.har.spec.json
agent/pkg/oas/utils.go

- Add `x-sample-entry` with last seen `MizuEntry.Id` to each operation
- Do not count negative durations (should only happen in tests)
- Re-parse query string params from URL, to be sure it is done right
- Follow symlinks in tests, for testing corpus excercises
- Only apply "ignore by name" to headers (it was ignoring some query string params by mistake)

OAS: Some minor fixes

---

.github/workflows/acceptance_tests.yml
.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/static_code_analysis.yml
.github/workflows/test.yml
Dockerfile
acceptanceTests/go.mod
agent/go.mod
cli/go.mod
devops/linux-arm64-musl-go-libpcap/Dockerfile
shared/go.mod
tap/api/go.mod
tap/extensions/amqp/go.mod
tap/extensions/http/go.mod
tap/extensions/kafka/go.mod
tap/extensions/redis/go.mod
tap/go.mod

Why so many indirect modules were added?
[Go 1.17 release notes](https://go.dev/doc/go1.17) 
> Because the number of explicit requirements may be substantially larger in an expanded Go 1.17 go.mod file, the newly-added requirements on indirect dependencies in a go 1.17 module are maintained in a separate require block from the block containing direct dependencies.

Moving to go 1.17

---

.github/workflows/acceptance_tests.yml

Motivation: get the exact commit where the acceptance tests started to fail

Removing concurrency group from acceptance test workflow

---

Makefile
cli/Makefile
tap/extensions/http/Makefile

parallel_process_count in mac is higher than linux and it causes problems when running it. 
so I used the -o flag and override the config to be "5" so it will work without need to change in every developer laptop.

Add help messages of make commands

---

Dockerfile

Fixes an index out of range error that occurs upon restoring the core in Basenine.
Can be tested by following these steps;
- `mizu install`
- Run load tests for a while (like 3 min)
- `mizu view`
- `kubectl rollout restart deployment mizu-api-server -n mizu`
- See the pods don't crash after the restart.
- `mizu view`

Upgrade Basenine version to `v0.4.16`

---

cli/cmd/viewRunner.go

The motivation for this change is to enable to run view against mizu enterprise

View command no version check

---

agent/pkg/controllers/service_map_controller_test.go
agent/pkg/servicemap/servicemap.go
agent/pkg/servicemap/servicemap_test.go

By default the node key is the entry.Name, when entry.Name is empty the node key will use the entry.IP as a fallback

Service Map node key as entry.Name instead of entry.IP

---

cli/Makefile

Introduced by the combination of:
- https://github.com/up9inc/mizu/pull/772
- https://github.com/up9inc/mizu/pull/754
Fixes the following error:
```
./cli/bin/mizu__ tap -n sock-shop                                                                                                                                                                                ok  19:16:09 
Mizu will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
Tapping pods in namespaces "sock-shop"
+carts-5fb6949d8c-cr4ts
+carts-db-6c6c68b747-sfns5
+catalogue-79fbdc774-rnfkr
+catalogue-db-96f6f6b4c-g7mg2
+front-end-5c89db9f57-j2fht
+kafka-0
+mizutest-amqp-py-bc8957cdf-cds5p
+mizutest-grpc-py-client-85c9bf7757-kn6tw
+mizutest-grpc-py-server-5947869cdf-4bj48 …
```

Don't statically link the CLI

---

cli/README.md.TEMPLATE

This should fix this issue:
On Mac M1 if you override the executable the OS refuse to execute and will kill it because of caching mechanism

Update relase template for Mac M1 executable

---

agent/go.mod
agent/go.sum
agent/pkg/oas/specgen_test.go
agent/pkg/oas/test_artifacts/params.har.spec.json

If we learned over time sufficient information to group endpoints together - do it. 
Remember historical OperationIDs into custom property.

OAS: Recluster endpoints where possible

---

Dockerfile
agent/go.mod
agent/go.sum
cli/go.mod
cli/go.sum

Brings in the fixes listed in the change log of these releases:
- https://github.com/up9inc/basenine/releases/tag/v0.5.4
- https://github.com/up9inc/basenine/releases/tag/v0.5.3

Upgrade Basenine version to `v0.5.4`

---

.github/workflows/build-custom-branch.yml

Currently developer with Mac M1 can't build Mizu docker image for AMD Architecture.
This is a workaround for now for these developers to build a custom docker image for testing
The build is triggered with '#build_and_publish_custom_image' in commit message, and will be published to gcr.io/up9-docker-hub/mizu/<branch name>:latest

Build custom branch Github action

---

Dockerfile
agent/go.mod
agent/go.sum
cli/go.mod
cli/go.sum

Introduced by https://github.com/up9inc/mizu/pull/891
No stable versions are affected.

Bump the version to `0.6.6` and fix the index shift bug that occurs after database truncation

---

agent/pkg/api/main.go

Prior to this PR Mizu sets the entry namespace to the namespace of the resolved destination.
However, sometimes the destination is not resolved while the source is. For instance, when the destination is an external address.
This PR adds the following logic:
If the destination is resolved and the namespace is not empty, use it.
Otherwise, if the source is resolved then use its namespace.
This change allows filtering by namespace to include entries which were previously left out unintentionally. The namespace  of a source is of interest to a user. 
Unhandled cases:
1. If both source and destination are resolved, then only the destination namespace is taken into account. A better solution would be to maintain two separate fields in the DB: source namespace and destination namespace.
2. Only …

Set the entry namespace to the source namespace if the destination is not resolved

---

agent/pkg/api/main.go
tap/passive_tapper.go
tap/source/packet_source_manager.go

- Read from service mesh network namespaces upon update (27a73e21fbad3c30ddf3562f70470bc1af2bb5b4)
- Set the entry namespace to the source namespace if the destination is not resolved (a49443f10104bc941c24910f14a9186c1457c24b)

Hotfix tap issues - restart service mesh tapping when when tap targets change, fallback to source namespace

---

.github/workflows/acceptance_tests.yml

Multi line commit messages break the slack message formatting. This PR fixes by formatting the commit message as `code`.
Before:
After:

Format commit message as code to handle multi line messages

---

tap/extensions/http/helpers.go

`reflect.TypeOf(value)` was returning `nil` in cases of `value` is `nil`. That was causing the error below:
```
mizu-api-server mizu-api-server 2022/04/04 12:42:15 [Recovery] 2022/04/04 - 12:42:15 panic recovered:
mizu-api-server mizu-api-server runtime error: invalid memory address or nil pointer dereference
mizu-api-server mizu-api-server /usr/local/go/src/runtime/panic.go:221 (0x44c746)
mizu-api-server mizu-api-server /usr/local/go/src/runtime/signal_unix.go:735 (0x44c716)
mizu-api-server mizu-api-server /app/tap/extensions/http/helpers.go:56 (0x1b5509c)
...
```
The PR fixes it.

Handle `reflect.TypeOf` returning `nil` case

---

.github/workflows/acceptance_tests.yml

Fixes the issue where we get alerts on failed acceptance tests by committer "github".

Use author instead of committer in slack alerts

---

tap/tcp_stream.go

TCP Keep Alive allows to reuse the same TCP connection for multiple messages.
Currently Mizu doesn't support it because the assembler of go-packet is strict by default, if it miss the initial SYN packet, it doesn't build a stream.
This PR tells go-packet to build a stream even if it misses the first SYN, and indirectly support TCP Keep Alive, and also Linkerd support which reuse the same TCP connection.

support tcp keep alive

---

shared/kubernetes/mizuTapperSyncer.go

This change will enable using mizu on clusters with custom names different than cluster.local.

Remove cluster.local hostnames

---

tap/settings.go
tap/tcp_streams_map.go

This PR will reduce the idle CPU usage. But it will **increase the out of memory (OOM) risk** under heavy traffic load.
60 seconds of CPU profiling:

Increase the OOM risk in exchange of less idle CPU usage

---

.github/workflows/test.yml
tap/api/api.go
tap/extensions/amqp/Makefile
tap/extensions/http/Makefile
tap/extensions/kafka/Makefile
tap/extensions/redis/Makefile

Now, those tests will run on pull request when there is change in tap/api folder.
I'm thinking about change it for any change in the "tap" folder so if tls folder or something else inside tap will change it will run too but not sure.
I didn't add the alert here because this should block the "merge" of PR so we shouldn't see cases when the it fails on develop after the merge

Run unit tests when tap/api changes 

---

Dockerfile
agent/go.mod
agent/go.sum
cli/go.mod
cli/go.sum

Fixes the memory usage issues in the `basenine` container, in case of long-term run.

Upgrade Basenine to `0.7.3`

---

cli/Makefile
cli/config/configStructs/tapConfig.go
cli/go.mod
cli/go.sum

Introduced by https://github.com/up9inc/mizu/pull/984
```
make[2]: Entering directory '/home/mertyildiran/Documents/up9/mizu/cli'
go build  -ldflags="-s -w \
-X 'github.com/up9inc/mizu/cli/mizu.GitCommitHash=9b475a78f9cd816080f0e633daa2940037ee63e2' \
-X 'github.com/up9inc/mizu/cli/mizu.Branch=develop' \
-X 'github.com/up9inc/mizu/cli/mizu.BuildTimestamp=1650460861' \
-X 'github.com/up9inc/mizu/cli/mizu.Platform=windows_amd64' \
-X 'github.com/up9inc/mizu/cli/mizu.Ver=0.0'" \
-o bin/mizu_windows_amd64 mizu.go
(cd bin && shasum -a 256 mizu_windows_amd64 > mizu_windows_amd64.sha256)
../../../../go/pkg/mod/github.com/up9inc/basenine/server/lib@v0.0.0-20220419100955-e2ca51087607/helpers.go:49:37: cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.Recvfrom …
```

Fix the CLI build error for Windows target

---

tap/api/go.mod
tap/extensions/amqp/go.mod
tap/extensions/http/go.mod
tap/extensions/kafka/go.mod
tap/extensions/redis/go.mod
tap/go.mod

Leftovers forgotten to remove, sourced from a merge conflict handled in https://github.com/up9inc/mizu/pull/1026 of changes in https://github.com/up9inc/mizu/pull/1047

Remove the obsolete `replace` statements that are artifacts of a merge conflict

---

tap/extensions/http/main.go

https://grpc.github.io/grpc/core/md_doc__p_r_o_t_o_c_o_l-_h_t_t_p2.html is a better reference link than https://grpc.github.io/grpc/core/md_doc_statuscodes.html that describes gRPC over HTTP2.

Replace the gRPC reference link with a better one

---

tap/extensions/kafka/Makefile
tap/extensions/kafka/helpers.go
tap/extensions/kafka/main.go
tap/extensions/kafka/request.go

Fix the Kafka `ApiKey` query and add `ApiKeyName` field (human-readable `ApiKey`)

---

tap/tcp_reader.go
tap/tcp_stream.go

Introduced by https://github.com/up9inc/mizu/pull/1062
Causing acceptance tests failures.
**No stable releases are affected.**
Fixes the error below that occurs in case of protocols other than HTTP:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2337d67]
goroutine 57 [running]:
github.com/up9inc/mizu/tap.(*tcpReader).populateData(0xc0004be5b0, {0x0, 0x0})
/home/mertyildiran/Documents/up9/mizu/tap/tcp_reader.go:95 +0x27
github.com/up9inc/mizu/tap.(*tcpReader).Read(0xc0004be5b0, {0xc00094c000, 0x1000, 0x7f853165ed28})
/home/mertyildiran/Documents/up9/mizu/tap/tcp_reader.go:112 +0x3d
bufio.(*Reader).Read(0xc00048a480, {0xc00038c290, 0x7, 0xd57d07})
/usr/local/go/src/bufio/bufio.go:227 +0x1b4 …
```

Fix a `nil pointer dereference` error that occurs in `tcpReader`'s `Read` method

---

tap/tlstapper/go_offsets.go

Introduced by https://github.com/up9inc/mizu/pull/1120

Fix a `slice bounds out of range` panic in Go offsets calculation

---

agent/pkg/api/socket_routes.go

```
2022/07/11 07:21:08 [Recovery] 2022/07/11 - 07:21:08 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:221 (0x44f026)
/usr/local/go/src/runtime/signal_unix.go:735 (0x44eff6)
/app/agent-build/pkg/api/socket_routes.go:154 (0x1632665)
/app/agent-build/pkg/api/socket_routes.go:100 (0x163221c)
/app/agent-build/pkg/api/socket_routes.go:125 (0x163216d)
/app/agent-build/pkg/api/socket_routes.go:68 (0x1631b64)
```

Fixed panic in socket cleanup

---

ui-common/src/components/EntryDetailed/EntryViewer/AutoRepresentation.tsx
ui-common/src/components/EntryDetailed/EntryViewer/SectionsRepresentation.tsx

after merging https://github.com/up9inc/mizu/pull/1091, when there is no response we see message of "This request or response has no data", I think better solution will be to hide the response tab completely.
(in the PR we talked about remove it but the solution was to remove the request too and in this solution the Request will always be there and response will be added when exists (like it was before)

Hide Response tab if there is no resepone

---

.github/workflows/release.yml

The current `set-output` syntax being used is deprecated and will be disabled on 2023-05-31 due to security concerns. See [GitHub Actions: Deprecating save-state and set-output commands | GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) for details. 
This change cleans up the syntax a bit and will get rid of the warning messages in the GitHub Actions logs.

Upgrade deprecated set-output GitHub Actions syntax to avoid warnings

---

.github/workflows/linter.yml
.github/workflows/release.yml
.github/workflows/test.yml

This updates several GitHub Actions versions and uses latest syntax for options on them:
- Upgrade `actions/checkout` to latest (`v3`) to avoid node version warnings
- Upgrade `actions/setup-go` to latest (`v4`) and use `go.mod` as the single source of truth for the go version
- Upgrade `golangci/golangci-lint-action` to latest (`v3`)
- Upgrade `codecov/codecov-action` to latest (`v3`)
- Upgrade `goreleaser/goreleaser-action` to latest (`v4`) and use `--clean` instead of deprecated `--rm-dist` (see [notice](https://goreleaser.com/deprecations/#-rm-dist))
If this would be better as separate PRs, definitely let me know.

Upgrade github actions versions to latest and update deprecated options

---

helm-chart/README.md
helm-chart/templates/06-front-pod.yaml
helm-chart/templates/12-nginx-config.yaml
helm-chart/values.yaml

I figured it would make sense to configure whether to use ipv6 or not. Currently - as we have not enabled ipv6 yet - I am unable to get kubeshark running

✨Allow to disable IPv6

---

Makefile
helm-chart/templates/01-service-account.yaml
helm-chart/templates/02-cluster-role.yaml
helm-chart/templates/03-cluster-role-binding.yaml
helm-chart/templates/04-hub-pod.yaml
helm-chart/templates/05-hub-service.yaml
helm-chart/templates/06-front-pod.yaml
helm-chart/templates/07-front-service.yaml
helm-chart/templates/08-persistent-volume-claim.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/10-ingress-class.yaml
helm-chart/templates/11-ingress.yaml
helm-chart/templates/12-nginx-config.yaml
helm-chart/templates/NOTES.txt
helm-chart/templates/_helpers.tpl
manifests/complete.yaml

This PR includes:
- standard labels using a `_helpers.tpl`  file to create those labels.
- removed all the `creationTimestamp` inputs.
- Included a `NOTES.txt` file to help users after the installing.
- Service Account Name also generated by `_helpers.tpl`  file.

:hammer: Add `_helpers.tpl` and `NOTES.txt` to Helm chart and refactor `labels`

---

helm-chart/templates/04-hub-pod.yaml
helm-chart/templates/05-hub-service.yaml
helm-chart/templates/06-front-pod.yaml
helm-chart/templates/13-module-loader.yaml
helm-chart/templates/14-module-loader-config-map.yaml
helm-chart/templates/kernel-module-management.yaml
helm-chart/values.yaml

- File generated from https://github.com/kubernetes-sigs/kernel-module-management/tree/main/config/default using
```
kubectl kustomize <folder>
```
- included kubeshark labels and checking
Attention, kernel module management requires [cert-manager.](https://cert-manager.io/docs/installation/helm/) operator.

:sparkles: Include kernel module management operator

---

config/configStructs/tapConfig.go
helm-chart/PF_RING.md
helm-chart/README.md
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/15-pf-ring-kernel-module.yaml
helm-chart/values.yaml

Towards https://github.com/kubeshark/kubeshark/issues/1458 and https://github.com/kubeshark/kubeshark/issues/1464
- two modes of running with pf_ring - auto and kmm
- possibility to load pf_ring kernel module via kernel module management controller
- automation for a custom module compilation
- tool to verify compatibility of cluster with pf_ring and build helper
@alongir if we ok with this - then I'll make https://github.com/kubeshark/pf-ring-compiler public

Add PF_RING related changes to docs and helm

---

helm-chart/README.md
helm-chart/values.yaml

As Tracer requires significantly more resources and elevated security capability, it is recommended to have it disabled by default and enabled on demand.

Tracer, ServiceMesh - Disable by default and some docs updates

---

helm-chart/templates/12-config-map.yaml
helm-chart/templates/_helpers.tpl

Global filter uses a single quote as opposed to double quote. This limits the use of `'` inside the string as it can not be escaped. When using double quote ("), single quote can be used and double quote can be escaped as part of a string. An example for a Global Filter string: "redact(\"request.headers.Authorization\", \"request.headers['X-Aws-Ec2-Metadata-Token']\")"

Global Filter, escaping doublequotes in strings

---

helm-chart/templates/06-front-deployment.yaml

Empty environment variables can not be read by front.

fix the env variable / helm issue

---

config/configStruct.go
helm-chart/values.yaml

during tracer ebpf perfbuf calls mmap(2) is required in some cases
found whet testing https://github.com/kubeshark/tracer/issues/20 on Linux 6.5.0

Add IPC_LOCK capability for tracer

---

.github/static/kubeshark.rb.tmpl
.github/workflows/release.yml

Towards https://github.com/kubeshark/kubeshark/issues/1488 and https://github.com/kubeshark/kubeshark/issues/1345
For now we're releasing two pairs of artifacts per platform: one compiled with make and another (binary) one with goreleaser (tar.gz). If I'm not mistaken, we do gorelease only to have brew tap updated automatically. But gorelease binaries don't have proper `kubeshark version` output as they are compiled without make and `VER=` variable set.
This PR:
1. Removes goreleaser job
2. Adds homebrew formulae template which is rendered with proper binary URLs and sha256 during release.
TODO:
- add deployment key into https://github.com/kubeshark/homebrew-kubeshark repo with write access
- add secret.HOMEBREW_SSH_KEY with private key part of deployment key
This approach was tested with …

Template homebrew formulae with proper binaries

---

helm-chart/templates/02-cluster-role.yaml
helm-chart/templates/03-cluster-role-binding.yaml

Towards https://github.com/kubeshark/kubeshark/issues/1481
I've used these values to be able to run two instances of kubeshark
values-default.yaml
```
tap:
proxy:
worker:
srvPort: 30001
metrics:
port: 49100
```
install: `helm upgrade --install kubeshark helm-chart --set tap.docker.tag=canary --values values-default.yaml --namespace default`
values-vol.yaml
```
tap:
proxy:
worker:
srvPort: 30002
metrics:
port: 49101%
```
install: `kubectl create namespace vol; helm upgrade --install kubeshark helm-chart --set tap.docker.tag=canary --values values-vol --namespace vol`
Metrics also work out of the box, the only think to get result for proper instance, query should include instance port
e.g.
for default namespace:
```
kubeshark_matched_pairs_total{instance=~".*:49100"}
```
for vol namespace …

Add namespace prefix to cluster scope resources

---

.github/workflows/release.yml

By default commiter token would use personal fork, but in this case we want to use kubeshark fork https://github.com/kubeshark/homebrew-core

Add kubeshark fork to use for homebrew release

---

Makefile

Close #1510
Pre-built binaries and checksum files are released at GitHub Releases.
https://github.com/kubeshark/kubeshark/releases
But checksum files for windows/amd64 have the following issues.
kubeshark.exe
kubeshark_windows_amd64.sha256
- The executable file name and the checksum file name don't conform to the naming convention
- We can't verify the pre-built binaries with checksum files because the pre-built binary name is different from the actual binary name
```console
$ cat kubeshark_windows_amd64.sha256
ea8fffa952bc8047f493469d024887ed80f966c0d74cf5fb039ea12f71174629  kubeshark_windows_amd64
```
```console
$ sha256sum -c kubeshark_windows_amd64.sha256
sha256sum: kubeshark_windows_amd64: No such file or directory
kubeshark_windows_amd64: FAILED open or read
sha256sum: WARNING: 1 …
```

fix: fix the asset name of the checksum file for windows/amd64

---

helm-chart/templates/11-nginx-config-map.yaml
helm-chart/templates/16-network-policies.yaml

**In addition to:**
https://github.com/kubeshark/kubeshark/pull/1514
**Fixes issue:**
```
Warning  Unhealthy  84s (x6 over 91s)  kubelet            Liveness probe failed: dial tcp 10.1.221.106:8080: connect: connection refused
Warning  Unhealthy  84s (x8 over 91s)  kubelet            Readiness probe failed: dial tcp 10.1.221.106:8080: connect: connection refused
Normal   Killing    84s (x2 over 89s)  kubelet            Container kubeshark-front failed liveness probe, will be restarted
```

🐛 Fix front nginx and network policies ports

---

helm-chart/templates/09-worker-daemon-set.yaml

after https://github.com/kubeshark/tracer/pull/50 tracers operates with netlink and requires network capture capabilities enabled

add net capabilities for tracer

---

helm-chart/templates/09-worker-daemon-set.yaml

to provide it NOT as the default option, but require an explicit indication
to use it. To use eBPF instead of AF-PACKET or PF-RING, use:
--set tap.packetCapture=ebpf

as eBPF is a significant feature that can impact many users, this PR is meant

---

helm-chart/templates/09-worker-daemon-set.yaml

This behavior can be reversed by setting the `tap.packetCapture`
to a specific source or manually adding the command line property:
`-disable-ebpf` to both the `worker` and the `tracer`

Use eBPF as a traffic capture source by default if cgroup V2 is enabled.

---

helm-chart/templates/09-worker-daemon-set.yaml
manifests/complete.yaml

Access to /etc/os-release is required in tracer to enable syscalls

Add /etc/os-release for tracer sysevents

---

config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/values.yaml

With the new addition of `tap.stopped` flag, the default value is set to true, causing Kubeshark to start with traffic capture disabled. Users can start traffic capture once they start the dashboard.

Slow start

---

config/configStruct.go

TCP dissector can be added as a helm value. This dissector shouldn't be used in production clusters, as enabling this dissector will consume enormous amounts of CPU and memory.
TODO: Have the TCP dissector adhere to pod targeting rules.

Disable TCP dissector by default

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/_helpers.tpl
helm-chart/values.yaml

Towards https://github.com/kubeshark/devops/issues/12
By default everything stays the same.
But if we set tagLocked=false, then instead of full version, only minor version will be used. Eg.. v52.3 for any v52.3.X.
If tag is set explicitly via tap.docker.tag - it will override any option no matter what's the value of tagLocked

Use major version as containers tag

---

helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/_helpers.tpl

Towards https://github.com/kubeshark/hub/issues/168
1. default
```
helm template helm-chart | grep SENTRY_ENABLED -A1
- name: SENTRY_ENABLED
value: 'false'
--
- name: SENTRY_ENABLED
value: 'false'
--
- name: SENTRY_ENABLED
value: 'false'
--
- name: REACT_APP_SENTRY_ENABLED
value: 'false'
```
2. internet connectivity overrides telemetry and sentry
```
helm template helm-chart --set internetConnectivity=false --set tap.telemetry.enabled=true --set tap.sentry.enabled=true | grep SENTRY_ENABLED -A1
- name: SENTRY_ENABLED
value: 'false'
--
- name: SENTRY_ENABLED
value: 'false'
--
- name: SENTRY_ENABLED
value: 'false'
--
- name: REACT_APP_SENTRY_ENABLED
value: 'false'
```
3. telemetry overrides sentry
```
helm template helm-chart --set internetConnectivity=true --set tap.telemetry.enabled=false …
```

Calculate sentry based on internet connectivity and telemetry

---

helm-chart/templates/09-worker-daemon-set.yaml

Towards https://github.com/kubeshark/worker/issues/284

Do not enable `-unixsocket` flag of worker if no tracer is running

---

helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/11-nginx-config-map.yaml

Please, refer to the corresponding issue.

🐛 Prevent `hub` host-not-found nginx upstream error in `front`

---

helm-chart/templates/06-front-deployment.yaml

Reverts kubeshark/kubeshark#1628

Revert "🐛 Prevent `hub` host-not-found nginx upstream error in `front`"

---

config/configStruct.go

as it can be confused with https
tlsx is a dissector for TLS handshakes and not
HTTPS dissector.

change the tlx dissector name to tlsx

---

config/config.go
config/configStruct.go
config/configStructs/tapConfig.go
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

This PR moves from the use of `tap.debug` to `logLevel` to give more control of what appears in the logs.
To achieve the same functionality of `tap.debug=true`, the following cane be used: `logLevel=debug`
The default log level is set to `warning`

from debug to logLevel

---

helm-chart/templates/09-worker-daemon-set.yaml

following reverting tracer version: https://github.com/kubeshark/worker/pull/478

removed the loglevel flag

---

config/configStructs/tapConfig.go
helm-chart/README.md
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

Current 5s is not enough for large envs.
It also probably makes sense to make it template, but then whole liveness/readiness would need to be templated.
So for now:
- change init to 15s
- change period to 10s
So we have to think about making templates looking more community helm charts templates

Update worker liveness/readiness config

---

config/configStructs/tapConfig.go

Add dest arg to pcap dump struct in order to fix the warning received when running the command with dest arg.

Add dest arg to pcap dump struct

---

cmd/pcapDumpRunner.go
config/configStructs/tapConfig.go

Look for workers in all the available namespaces in order to make sure that none of them are skipped when the backend settings are changed to target or exclude some of the namespaces.
Remove gopacket from the merging operation in order to increase the performance.

Fix error on getting namespaces for pcap target files

---

helm-chart/templates/09-worker-daemon-set.yaml

to the worker daemon set, when `tap.tls=false` is set.

added `-disable-tracer` option

---

helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/values.yaml

Changes:
* add `tap.mountBpf` parameter to activate first init container
* removed second init container
* removed deprecated `-unixsocket` worker argument
* removed deprecated `-disable-ebpf` worker and tracer arguments
resolves https://github.com/kubeshark/worker/issues/540 
resolves https://github.com/kubeshark/devops/issues/34
see also https://github.com/kubeshark/worker/pull/544

Remove init container; remove -disable-ebpf option

---

helm-chart/README.md
helm-chart/values.yaml

Sentry is enabled by default for qualified users, and depending on the license tier.
Having Sentry enabled sends rich telemetry enabling better support.

Sentry Enabled By Default

---

cmd/scripts.go

Towards https://github.com/kubeshark/devops/issues/56
Also towards https://github.com/kubeshark/devops/issues/55 as it is small change - switch warning to debug as there is nothing to be warned about, program never fails when there is conflict, just retries again

Exit properly from scripts command

---

cmd/config.go
cmd/root.go
config/config.go

Build the CLI program with:
```sh
$ make
```
Print the help message:
```sh
$ ./bin/kubeshark__ --help
...
Flags:
--config-path string   Set the config path, default: /home/mertyildiran/.kubeshark/config.yaml
-d, --debug                Enable debug mode
-h, --help                 help for kubeshark
--set strings          Override values using --set
Use "kubeshark [command] --help" for more information about a command.
```
There are three possible options for the config path;
Usage examples of `--config-path` flag:
```sh
$ ./bin/kubeshark__ config -r --config-path ~/Downloads/kubeshark_config_example.yaml
2025-04-13T00:08:37+03:00 INF versionCheck.go:23 > Checking for a newer version...
2025-04-13T00:08:37+03:00 INF config.go:30 > Template file written to config path. …
```

Add `--config-path` flag to root command

---

helm-chart/templates/01-service-account.yaml
helm-chart/templates/02-cluster-role.yaml
helm-chart/templates/03-cluster-role-binding.yaml
helm-chart/templates/04-hub-deployment.yaml
helm-chart/templates/05-hub-service.yaml
helm-chart/templates/06-front-deployment.yaml
helm-chart/templates/07-front-service.yaml
helm-chart/templates/08-persistent-volume-claim.yaml
helm-chart/templates/09-worker-daemon-set.yaml
helm-chart/templates/17-network-policies.yaml
helm-chart/templates/18-dex-deployment.yaml
helm-chart/templates/19-dex-service.yaml

Towards https://github.com/kubeshark/kubeshark/issues/1763
- use annotations only when specified
- use pull secret on service account instead of deployments/daemonsets

Fix bugs in helm chart

---

helm-chart/templates/04-hub-deployment.yaml

Towards https://github.com/kubeshark/hub/issues/406
Current template treats 0 as null and therefore default value is used

Treat 0 value as 0s for dorman timeout
